// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Backoff is an autogenerated mock type for the Backoff type
type Backoff struct {
	mock.Mock
}

type Backoff_Expecter struct {
	mock *mock.Mock
}

func (_m *Backoff) EXPECT() *Backoff_Expecter {
	return &Backoff_Expecter{mock: &_m.Mock}
}

// Duration provides a mock function with no fields
func (_m *Backoff) Duration() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Duration")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// Backoff_Duration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Duration'
type Backoff_Duration_Call struct {
	*mock.Call
}

// Duration is a helper method to define mock.On call
func (_e *Backoff_Expecter) Duration() *Backoff_Duration_Call {
	return &Backoff_Duration_Call{Call: _e.mock.On("Duration")}
}

func (_c *Backoff_Duration_Call) Run(run func()) *Backoff_Duration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Backoff_Duration_Call) Return(_a0 time.Duration) *Backoff_Duration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Backoff_Duration_Call) RunAndReturn(run func() time.Duration) *Backoff_Duration_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function with no fields
func (_m *Backoff) Reset() {
	_m.Called()
}

// Backoff_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type Backoff_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
func (_e *Backoff_Expecter) Reset() *Backoff_Reset_Call {
	return &Backoff_Reset_Call{Call: _e.mock.On("Reset")}
}

func (_c *Backoff_Reset_Call) Run(run func()) *Backoff_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Backoff_Reset_Call) Return() *Backoff_Reset_Call {
	_c.Call.Return()
	return _c
}

func (_c *Backoff_Reset_Call) RunAndReturn(run func()) *Backoff_Reset_Call {
	_c.Run(run)
	return _c
}

// Wait provides a mock function with given fields: ctx
func (_m *Backoff) Wait(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Backoff_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type Backoff_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Backoff_Expecter) Wait(ctx interface{}) *Backoff_Wait_Call {
	return &Backoff_Wait_Call{Call: _e.mock.On("Wait", ctx)}
}

func (_c *Backoff_Wait_Call) Run(run func(ctx context.Context)) *Backoff_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Backoff_Wait_Call) Return(_a0 error) *Backoff_Wait_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Backoff_Wait_Call) RunAndReturn(run func(context.Context) error) *Backoff_Wait_Call {
	_c.Call.Return(run)
	return _c
}

// NewBackoff creates a new instance of Backoff. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBackoff(t interface {
	mock.TestingT
	Cleanup(func())
}) *Backoff {
	mock := &Backoff{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
