// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Limiter is an autogenerated mock type for the Limiter type
type Limiter struct {
	mock.Mock
}

type Limiter_Expecter struct {
	mock *mock.Mock
}

func (_m *Limiter) EXPECT() *Limiter_Expecter {
	return &Limiter_Expecter{mock: &_m.Mock}
}

// Acquire provides a mock function with given fields: ctx
func (_m *Limiter) Acquire(ctx context.Context) bool {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Acquire")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Limiter_Acquire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Acquire'
type Limiter_Acquire_Call struct {
	*mock.Call
}

// Acquire is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Limiter_Expecter) Acquire(ctx interface{}) *Limiter_Acquire_Call {
	return &Limiter_Acquire_Call{Call: _e.mock.On("Acquire", ctx)}
}

func (_c *Limiter_Acquire_Call) Run(run func(ctx context.Context)) *Limiter_Acquire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Limiter_Acquire_Call) Return(_a0 bool) *Limiter_Acquire_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Limiter_Acquire_Call) RunAndReturn(run func(context.Context) bool) *Limiter_Acquire_Call {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function with no fields
func (_m *Limiter) Release() {
	_m.Called()
}

// Limiter_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type Limiter_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
func (_e *Limiter_Expecter) Release() *Limiter_Release_Call {
	return &Limiter_Release_Call{Call: _e.mock.On("Release")}
}

func (_c *Limiter_Release_Call) Run(run func()) *Limiter_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Limiter_Release_Call) Return() *Limiter_Release_Call {
	_c.Call.Return()
	return _c
}

func (_c *Limiter_Release_Call) RunAndReturn(run func()) *Limiter_Release_Call {
	_c.Run(run)
	return _c
}

// NewLimiter creates a new instance of Limiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Limiter {
	mock := &Limiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
