// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	net "net"

	mock "github.com/stretchr/testify/mock"
)

// Stream is an autogenerated mock type for the Stream type
type Stream struct {
	mock.Mock
}

type Stream_Expecter struct {
	mock *mock.Mock
}

func (_m *Stream) EXPECT() *Stream_Expecter {
	return &Stream_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: ctx, conn
func (_m *Stream) Handle(ctx context.Context, conn net.Conn) {
	_m.Called(ctx, conn)
}

// Stream_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type Stream_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - conn net.Conn
func (_e *Stream_Expecter) Handle(ctx interface{}, conn interface{}) *Stream_Handle_Call {
	return &Stream_Handle_Call{Call: _e.mock.On("Handle", ctx, conn)}
}

func (_c *Stream_Handle_Call) Run(run func(ctx context.Context, conn net.Conn)) *Stream_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(net.Conn))
	})
	return _c
}

func (_c *Stream_Handle_Call) Return() *Stream_Handle_Call {
	_c.Call.Return()
	return _c
}

func (_c *Stream_Handle_Call) RunAndReturn(run func(context.Context, net.Conn)) *Stream_Handle_Call {
	_c.Run(run)
	return _c
}

// NewStream creates a new instance of Stream. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStream(t interface {
	mock.TestingT
	Cleanup(func())
}) *Stream {
	mock := &Stream{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
