// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BufferPool is an autogenerated mock type for the BufferPool type
type BufferPool struct {
	mock.Mock
}

type BufferPool_Expecter struct {
	mock *mock.Mock
}

func (_m *BufferPool) EXPECT() *BufferPool_Expecter {
	return &BufferPool_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with no fields
func (_m *BufferPool) Get() *[]byte {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *[]byte
	if rf, ok := ret.Get(0).(func() *[]byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]byte)
		}
	}

	return r0
}

// BufferPool_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type BufferPool_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *BufferPool_Expecter) Get() *BufferPool_Get_Call {
	return &BufferPool_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *BufferPool_Get_Call) Run(run func()) *BufferPool_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BufferPool_Get_Call) Return(_a0 *[]byte) *BufferPool_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BufferPool_Get_Call) RunAndReturn(run func() *[]byte) *BufferPool_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: _a0
func (_m *BufferPool) Put(_a0 *[]byte) {
	_m.Called(_a0)
}

// BufferPool_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type BufferPool_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - _a0 *[]byte
func (_e *BufferPool_Expecter) Put(_a0 interface{}) *BufferPool_Put_Call {
	return &BufferPool_Put_Call{Call: _e.mock.On("Put", _a0)}
}

func (_c *BufferPool_Put_Call) Run(run func(_a0 *[]byte)) *BufferPool_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*[]byte))
	})
	return _c
}

func (_c *BufferPool_Put_Call) Return() *BufferPool_Put_Call {
	_c.Call.Return()
	return _c
}

func (_c *BufferPool_Put_Call) RunAndReturn(run func(*[]byte)) *BufferPool_Put_Call {
	_c.Run(run)
	return _c
}

// NewBufferPool creates a new instance of BufferPool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBufferPool(t interface {
	mock.TestingT
	Cleanup(func())
}) *BufferPool {
	mock := &BufferPool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
