// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	model "github.com/sanchey92/flowgate/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// Balancer is an autogenerated mock type for the Balancer type
type Balancer struct {
	mock.Mock
}

type Balancer_Expecter struct {
	mock *mock.Mock
}

func (_m *Balancer) EXPECT() *Balancer_Expecter {
	return &Balancer_Expecter{mock: &_m.Mock}
}

// Pick provides a mock function with no fields
func (_m *Balancer) Pick() (*model.Backend, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Pick")
	}

	var r0 *model.Backend
	var r1 error
	if rf, ok := ret.Get(0).(func() (*model.Backend, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *model.Backend); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Backend)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Balancer_Pick_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pick'
type Balancer_Pick_Call struct {
	*mock.Call
}

// Pick is a helper method to define mock.On call
func (_e *Balancer_Expecter) Pick() *Balancer_Pick_Call {
	return &Balancer_Pick_Call{Call: _e.mock.On("Pick")}
}

func (_c *Balancer_Pick_Call) Run(run func()) *Balancer_Pick_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Balancer_Pick_Call) Return(_a0 *model.Backend, _a1 error) *Balancer_Pick_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Balancer_Pick_Call) RunAndReturn(run func() (*model.Backend, error)) *Balancer_Pick_Call {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function with given fields: backend
func (_m *Balancer) Release(backend *model.Backend) {
	_m.Called(backend)
}

// Balancer_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type Balancer_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - backend *model.Backend
func (_e *Balancer_Expecter) Release(backend interface{}) *Balancer_Release_Call {
	return &Balancer_Release_Call{Call: _e.mock.On("Release", backend)}
}

func (_c *Balancer_Release_Call) Run(run func(backend *model.Backend)) *Balancer_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Backend))
	})
	return _c
}

func (_c *Balancer_Release_Call) Return() *Balancer_Release_Call {
	_c.Call.Return()
	return _c
}

func (_c *Balancer_Release_Call) RunAndReturn(run func(*model.Backend)) *Balancer_Release_Call {
	_c.Run(run)
	return _c
}

// NewBalancer creates a new instance of Balancer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBalancer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Balancer {
	mock := &Balancer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
