// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	model "github.com/sanchey92/flowgate/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// Snapshotter is an autogenerated mock type for the Snapshotter type
type Snapshotter struct {
	mock.Mock
}

type Snapshotter_Expecter struct {
	mock *mock.Mock
}

func (_m *Snapshotter) EXPECT() *Snapshotter_Expecter {
	return &Snapshotter_Expecter{mock: &_m.Mock}
}

// Snapshot provides a mock function with no fields
func (_m *Snapshotter) Snapshot() []*model.Backend {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Snapshot")
	}

	var r0 []*model.Backend
	if rf, ok := ret.Get(0).(func() []*model.Backend); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Backend)
		}
	}

	return r0
}

// Snapshotter_Snapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshot'
type Snapshotter_Snapshot_Call struct {
	*mock.Call
}

// Snapshot is a helper method to define mock.On call
func (_e *Snapshotter_Expecter) Snapshot() *Snapshotter_Snapshot_Call {
	return &Snapshotter_Snapshot_Call{Call: _e.mock.On("Snapshot")}
}

func (_c *Snapshotter_Snapshot_Call) Run(run func()) *Snapshotter_Snapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Snapshotter_Snapshot_Call) Return(_a0 []*model.Backend) *Snapshotter_Snapshot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Snapshotter_Snapshot_Call) RunAndReturn(run func() []*model.Backend) *Snapshotter_Snapshot_Call {
	_c.Call.Return(run)
	return _c
}

// NewSnapshotter creates a new instance of Snapshotter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSnapshotter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Snapshotter {
	mock := &Snapshotter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
