// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	model "github.com/sanchey92/flowgate/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// Sourcer is an autogenerated mock type for the Sourcer type
type Sourcer struct {
	mock.Mock
}

type Sourcer_Expecter struct {
	mock *mock.Mock
}

func (_m *Sourcer) EXPECT() *Sourcer_Expecter {
	return &Sourcer_Expecter{mock: &_m.Mock}
}

// Load provides a mock function with no fields
func (_m *Sourcer) Load() ([]*model.Backend, uint64) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 []*model.Backend
	var r1 uint64
	if rf, ok := ret.Get(0).(func() ([]*model.Backend, uint64)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*model.Backend); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Backend)
		}
	}

	if rf, ok := ret.Get(1).(func() uint64); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(uint64)
	}

	return r0, r1
}

// Sourcer_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type Sourcer_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *Sourcer_Expecter) Load() *Sourcer_Load_Call {
	return &Sourcer_Load_Call{Call: _e.mock.On("Load")}
}

func (_c *Sourcer_Load_Call) Run(run func()) *Sourcer_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Sourcer_Load_Call) Return(_a0 []*model.Backend, _a1 uint64) *Sourcer_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Sourcer_Load_Call) RunAndReturn(run func() ([]*model.Backend, uint64)) *Sourcer_Load_Call {
	_c.Call.Return(run)
	return _c
}

// NewSourcer creates a new instance of Sourcer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSourcer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Sourcer {
	mock := &Sourcer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
